version: '3.7'
services:
    webserver:
        image: ghcr.io/chasers2012/docker-airflow-1/airflow:2.2.1
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_HOST=172.17.0.1
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8082:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
